[package]
name = "lsys-core-macros"
version = "0.0.1"
edition = "2021"
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.109", features = ["full"] }
quote = "1.0.38"
proc-macro2 = "1.0.93"
heck = "0.5.0"
