

#app_host="127.0.0.1"
#app_port=8080
#app_ssl_port=443
#app_ssl_cert = "config/lsys.cc_bundle.crt"
#app_ssl_key = "config/lsys.cc.key"
#日志配置
log_level = "sqlx_core=info,lsys_app_sender=debug,lsys_app=trace,axtix_web=debug,actix=info,mio=error,lsys_access=trace,lsys_web=trace,lsys_core=trace,lsys_user=trace,lsys_rbac=trace,lsys_docs=trace,lsys_actix_web=trace,sqlx=trace,redis=debug,lsys_app_barcode=trace"
log_dir = "logs"
log_name = "app"
#数据库配置
#database_url="mysql://root:000@127.0.0.1:3306/test"
#公共表前缀
database_table_prefix = "yaf_"
#redis 配置
#redis_url="redis://127.0.0.1/"

#是否使用LUA缓存
use_cache = false

#二维码最大内容长度
barcode_create_max = 500

#静态文件目录
ui_dir = "../../../ui/public/"
#静态文件访问路径,默认:/ui/
#ui_path="/ui/"
ui_path = "/"
#超级管理员id,user表id
root_user_id = [1]

#语言文件目录
fluent_dir = "locale/"

#页面模板目录
tpl_dir = "./static"

#静态文件保存目录
static_file_dir = "./static"

#地址库数据文件压缩包
area_code_db = "data/2023-7-area-code.csv.gz"
#地址库数据文件压缩包
area_geo_db = "data/2023-7-area-geo.csv.gz"
#地址库索引文件目录
# area_index_dir = "/tmp/area_index"
#地址库索引时使用内存大小
# area_index_size = 500_000_000

# ip城市数据
# 下载以下文件解压后得到
# IP2LOCATION-LITE-DB11.BIN.zip 
ip_city_db = "data/IP2LOCATION-LITE-DB11.BIN"

#发送邮件 短信 生成唯一ID用
#snowflake_machine_id=1 #最大31
#snowflake_node_id=1 #最大31

# jwt token 
#app_jwt_key = "bbb" #jwt 密钥


#接口允许域名
api-allow-origin = "*"
